# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('returns', models.FloatField(default=0.0)),
                ('risk', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
